### PR TITLE
(7.9.0) INFRASYS-5532: Reduced timeout from 1000 to 500 seconds, added iterat…

### PR DESCRIPTION
**Pull request by jbravo-tejeda**
…ion counter in order to break tomcat restart while loop incase of failure

### CODE REVIEW

**Comment by mjgorman** [comment]
+1

**Comment by kantselovich** [comment]
+1  when rebases against  #10

**Comment by jbravo-tejeda** [comment]
Master has been merged into the feature branch.

**Comment by jbravo-tejeda** [comment]
I rebased against master instead of merging master into the feature branch. The code result is the same. The tests that are failing ARE NOT due to these code changes so this can be merged.

**Comment by kantselovich** [comment]
we will merge this, as now testing is not quite working yet

**Pull request merged**
