### PR TITLE
INFRASYS-5596 Write working tomcat restart tests with python 2.7

### PR DESCRIPTION
**Pull request by mjgorman**

### CODE REVIEW

**Comment by mjgorman** [comment]
Tests are passing for python 2.7.  https://travis-ci.org/dandb/pytomcat/jobs/67241471 Another ticket is being opened for additional work to insure compatibility with 2.6 testing framework.  This is considered done.

**Comment by kantselovich** [comment]
+1  Thank you @mjgorman

**Comment by sbraverman** [comment]
+1

**Comment by adamjkeller** [comment]
+1

**Pull request merged**
