### PR TITLE
(8.0.0) INFRASYS-5544: Working TRAVIS-CI test build with PyTomcat

### PR DESCRIPTION
**Pull request by jbravo-tejeda**

### CODE REVIEW

**Comment by mjgorman** [comment]
+1 on getting travisCi working. I think fixing the remaining test issues can be a separate endeavor.

**Comment by jbravo-tejeda** [comment]
Please ignore failures. The work here is to introduce TRAVIS-CI functionality, regardless of whether Tomcat tests fail. That will be fixed later in another sprint.

**Comment by kantselovich** [comment]
+1   
- could you add comment README so we see "build passing"  mark
-  could you move 'wget'  into  setup.py,  so  calling ``python setup.py install``  would install all the dependencies.   Otherwise installation becomes travis-ci  specific,  which is  not the best option.

**Comment by jbravo-tejeda** [comment]
@kantselovich I just made the changes, please review. Thanks!

**Pull request merged**
